### ISSUE TITLE
Epic - Modding

### ISSUE THREAD

**Issue by GalacticChimp** [Adeptus-Dominus/ChapterMaster#250]
**Description**

Currently, CM is non-moddable (apart from adding custom icons). The code doesn't allow to do anything related to modding without large rewrites.

The goal is to do these rewrites, one by one. The final version should allow modding:

- [ ] Weapons, items, gear etc. (both enemy and player's, since all items should be treated agnostically)
- [ ] Vehicles
- [ ] Ships
- [ ] names (character, planet, etc.)
- [ ] Characters (traits, stat distribution, experience thresholds, etc)
- [ ] psyker powers / chaos magic
- [ ] Chapters (including codex adherance, company structure, (dis)advantages, etc)
- [ ] Factions (or at least subfactions, created from a main factions template, e.g. Ordo Xenos created from the general Inquisition template)
- [ ] Scenarios
- [ ] Events
- [ ] Tech tree
- [ ] general game settings and definitions (starting requistion, enemy aggression level etc.)

all of the above should have matching changes in the UI, e.g. the Shop item list should be scrollable, to allow trading arbitrary number of items.

the above entities might have some limitations set on them where appropriate, for example chapter (dis)advantages can only be defined from a predefined list of effects and triggers.

**Issue list**

- [ ] #237 
- [x] #197 
- [ ] #248 (this is needed to allow save files to support modded stuff)
- [x] #204 
- [ ] TODO many, many more

**Comment by Blogaugis** [comment]
Adding to Weapons, items and gear:
A good idea would be to allow shop menu to be scroll-able.
In other words, if we want to make 100s of various of imperial and not imperial weapons to be build-able, we need some way to expand the showed options, as in the current 3 screens, these wouldn't fit.
Of course, that also asks for equipment screen rework as well, to actually appear as options when equipping marines.

**Comment by GalacticChimp** [comment]
> ...snip...

added to description
